language: rust


matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu FEATURE_FLAGS="linux-static-libusb"

    - env: TARGET=x86_64-unknown-linux-gnu FEATURE_FLAGS="linux-static-hidraw"

    - env: TARGET=x86_64-unknown-linux-gnu FEATURE_FLAGS="linux-shared-libusb"

    - env: TARGET=x86_64-unknown-linux-gnu FEATURE_FLAGS="linux-shared-hidraw"

    - env: TARGET=x86_64-apple-darwin
      os: osx


script:
  - cargo build --verbose --no-default-features --features="${FEATURE_FLAGS}"
  - cargo test --verbose --no-default-features --features="${FEATURE_FLAGS}"

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libudev-dev
      - libhidapi-dev